### ISSUE TITLE
2.0.0-beta3: Cannot find module './src/jasmine-matchers'

### ISSUE THREAD

**Issue by mull** [JamieMason/Jasmine-Matchers#51]
Hi folks. Just noticed this error after installing beta3. Was not present in beta2. Hope it helps! Let me know if I can provide additional assistance. :-)

```
Users/eml/Projects/qlearning/qlearning_webapp/node_modules/jasmine-expect/index.js: Cannot find module './src/jasmine-matchers' from '/Users/eml/Projects/project/node_modules/jasmine-expect/index.js'
  at Loader._getNormalizedModuleID (/Users/eml/Projects/project/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:349:15)
  at Loader._shouldMock (/Users/eml/Projects/project/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:558:23)
  at Loader.requireModuleOrMock (/Users/eml/Projects/project/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:920:12)
  at Object.<anonymous> (/Users/eml/Projects/project/node_modules/jasmine-expect/index.js:3:18)
  at Object.runContentWithLocalBindings (/Users/eml/Projects/project/node_modules/jest-cli/src/lib/utils.js:527:17)
  at Loader._execModule (/Users/eml/Projects/project/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
  at Loader.requireModule (/Users/eml/Projects/project/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
  at Loader._generateMock (/Users/eml/Projects/project/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:270:30)
  at Loader.requireMock (/Users/eml/Projects/project/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:798:43)
  at Loader.requireModuleOrMock (/Users/eml/Projects/project/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:921:17)
  at Object.<anonymous> (/Users/eml/Projects/project/__tests__/client/utils/testQlearningApiSpec.js:2:117)
  at Object.runContentWithLocalBindings (/Users/eml/Projects/project/node_modules/jest-cli/src/lib/utils.js:527:17)
  at Loader._execModule (/Users/eml/Projects/project/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:239:9)
  at Loader.requireModule (/Users/eml/Projects/project/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:902:12)
  at jasmineTestRunner (/Users/eml/Projects/project/node_modules/jest-cli/src/jasmineTestRunner/jasmineTestRunner.js:284:16)
  at /Users/eml/Projects/project/node_modules/jest-cli/src/TestRunner.js:379:12
```

**Comment by JamieMason** [comment]
Apologies, [this](https://github.com/JamieMason/Jasmine-Matchers/blob/818a48da73d21ce40effab9d23b385c8e719d20a/.npmignore#L3) was missing. I've fixed this and released 2.0.0-beta4.

**Comment by Szpadel** [comment]
Hello @JamieMason 

I have beta4 installed and the issue is still present.
Could you double check this?

**Comment by mull** [comment]
I also saw this failing for beta4

**Comment by JamieMason** [comment]
You're right @Szpadel @mull. Addressing it now, sorry about this.

**Comment by mull** [comment]
No worries. I can test this within the next ~3 hrs (or tomorrow), let me know when you release and I'll see if it works :)

**Comment by JamieMason** [comment]
Just published `jasmine-expect@2.0.0-beta5` 

\*shakes head\* normally I'm more thorough, but I rushed this.

**Comment by JamieMason** [comment]
karma-jasmine-matchers updated to 2.0.0-beta5 as well.

**Comment by Szpadel** [comment]
With beta5 it's working fine, thanks.

**Comment by mull** [comment]
Works. Though I ran into a small problem, for some reason, that Jest started auto-mocking the module all of a sudden. It didn't before. Anyhow, I just added it to the list of unmocked packages and all is fine. Thanks for the work @JamieMason!

**Comment by JamieMason** [comment]
Phew, great. 

@mull would you mind showing how Jasmine-Matchers can be used with Jest? Someone mentioned before that they're compatible, but I've never seen for myself how it works.

Thanks.

**Comment by mull** [comment]
@JamieMason sure.

```json
// package.json
"unmockedModulePathPatterns": [
  "jasmine-expect"
],
```

```js
//some test
import JasmineExpect from 'jasmine-expect';

...
  expect(uniList).toBeNonEmptyArray();
  expect(uniList).toBeArrayOfObjects();
```

Not any harder than that. AFAIK we're doing nothing special :-) We're moving away from Jest though, absolutely hate it!

**Comment by JamieMason** [comment]
Thanks a lot @mull that's useful (may add it to the README). We looked at Jest at work for a while but decided against it in the end. The idea of automatic mocking though did sound like it could be quite nice.

**Comment by mull** [comment]
No problem! It is kind of nice sometimes. Jest is buggy though, and some of the options in the docs don't quite work. Especially combined with other options (one is somehow overriding the other.) It's been a messy journey so far.

**Comment by JamieMason** [comment]
Good to know, I think I'll steer clear.

**Comment by reintroducing** [comment]
Is there any way to do this in a test-setup.js file that is executed with the [setupFiles](https://facebook.github.io/jest/docs/configuration.html#setupfiles-array) command from Jest? I'd like to just import this once and not have to worry about it in every single test file.

As of right now the only way I can get this working is to do this in each test file:

`import JasmineExpect from 'jasmine-expect'; // eslint-disable-line no-unused-vars`

It's kind of tedious and I expect another developer on the team will forget at some point and wonder why his tests are failing.

**Comment by JamieMason** [comment]
I'll push an example up soon but the config you need I @reintroducing  think is `setupTestFrameworkScriptFile`

```json
{
  "devDependencies": {
    "jasmine-expect": "*",
    "jest": "18.1.0"
  },
  "jest": {
    "setupTestFrameworkScriptFile": "<rootDir>/node_modules/jasmine-expect/index.js",
    "verbose": true
  },
  "private": true,
  "scripts": {
    "test": "jest"
  }
}
```

**Comment by JamieMason** [comment]
Example added: https://github.com/JamieMason/Jasmine-Matchers/commit/12e464c305f1f66706c929424023629d60245256.

**Comment by reintroducing** [comment]
That worked perfectly @JamieMason, thank you and thanks for this module, it's been a huge help when writing Jasmine tests previously and now with using Jest as well.

**Comment by JamieMason** [comment]
You're welcome, thanks.
